on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout branch
        uses: actions/checkout@v1
      - name: Build project
        run: make
      - name: Run tests
        run: make test
        
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/deepfinder
    permissions:
      id-token: write
    steps:

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
